name: Build Documentation and Deploy
on:
  push:
    branches:
      - main
      - feature/switch_gh_pages_docker

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cuvis AI
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker build -t "cuvis_ai" .
      - name: Run docker container and build Documentations
        run: docker run --mount type=bind,source="$(pwd)"/docs,target=/app/docs cuvis_ai /bin/bash  /app/build_docs.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/_build/html/
