name: Build Documentation and Deploy
on:
  push:
    branches:
      - main
      - feature/switch_gh_pages_docker

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: cubertgmbh/cuvis_python:3.3.1-ubuntu22.04
    steps:
      - name: Checkout Cuvis AI
        uses: actions/checkout@v4
      - name: Install Cuvis AI
        run: |
          python3.10 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          python3.10 -m pip install .
          python3.10 -m pip install -r docs/requirements.txt
          python3.10 -m pip show cuvis
          export CUVIS=/lib/cuvis
          echo "Test Cuvis AI importable"
          python3.10 -c "import cuvis; import cuvis_ai"
      - name: Build Documentation
        run: |
          export CUVIS=/lib/cuvis
          mkdir -p docs/_build
          sphinx-build -M html docs docs/_build
          touch docs/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/_build/html/
