name: Build Documentation and Deploy
on:
  push:
    branches:
      - main
      - feature/fix_gh_deploy

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build docker images
        run: docker build -t "cuvis_ai" .
      - name: Make empty dir
        run: mkdir -p ./docs/_build
      - name: Run docker container
        run: docker run -v ./docs/_build:/install/cuvis.ai/docs/_build cuvis_ai /bin/bash  /install/cuvis.ai/entrypoint_doc.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: ./docs/_build/html/

