name: Build Documentation and Deploy
on:
  push:
    branches:
      - main
      - feature/fix_gh_deploy

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cuvis AI
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.10 python3.10-venv
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
          python3.10 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          python3.10 -m pip install .
          python3.10 -m pip install -r docs/requirements.txt
          echo "Test Cuvis AI importable"
          python3.10 -c "import cuvis; import cuvis_ai"
      - name: Build Documentation
        run:  |
            mkdir -p docs/_build
            sphinx-build -M html docs docs/_build
            touch docs/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/_build/html/

