name: Build Documentation and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build
        run: |
          mkdir _build
          cmake -B ./_build .
          cmake --build "_build"
          touch ./_build/doc/sphinx/.nojekyll
          

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./_build/doc/sphinx

