name: Build Documentation and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build
        run: |
		  make html
          touch docs/_build/html/.nojekyll
          

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/_build/html/

